CREATE TABLE IF NOT EXISTS Organization(
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  version INTEGER NOT NULL,                                                                                                          name VARCHAR(30) UNIQUE NOT NULL,
  full_name VARCHAR(50) UNIQUE NOT NULL,
  inn VARCHAR(12) UNIQUE NOT NULL,
  kpp VARCHAR(9) UNIQUE NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  is_active BOOLEAN
  );

CREATE TABLE IF NOT EXISTS Office(
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  version INTEGER NOT NULL,
  org_id INTEGER NOT NULL,
  name VARCHAR(30) UNIQUE NOT NULL,
  address VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  is_active BOOLEAN
  );

CREATE TABLE IF NOT EXISTS User(
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  version INTEGER NOT NULL,
  office_id INTEGER NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  second_name VARCHAR(50) NOT NULL,
  middle_name VARCHAR(50),
  position VARCHAR(50) NOT NULL,
  citizenship_id INTEGER ,
  is_identified BOOLEAN
  );

CREATE TABLE IF NOT EXISTS Doc_type(
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
  code VARCHAR(2) NOT NULL,
  name VARCHAR(255) NOT NULL
  );

CREATE TABLE IF NOT EXISTS Document(
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL ,
  user_id INTEGER NOT NULL,
  doc_type INTEGER NOT NULL,
  doc_number VARCHAR(20) NOT NULL,
  doc_date DATE
  );

CREATE TABLE IF NOT EXISTS Citizenship(
  id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL ,
  code VARCHAR(3),
  name VARCHAR(255) NOT NULL
  );

CREATE INDEX IX_OFFICE_ORG_ID ON OFFICE(ORG_ID);
ALTER TABLE OFFICE ADD FOREIGN KEY (ORG_ID) REFERENCES ORGANIZATION(ID);

CREATE INDEX IX_USER_OFFICE_ID ON USER(OFFICE_ID);
ALTER TABLE USER ADD FOREIGN KEY (OFFICE_ID) REFERENCES OFFICE(ID);

CREATE INDEX IX_USER_CITIZENSHIP_ID ON USER(CITIZENSHIP_ID);
ALTER TABLE USER ADD FOREIGN KEY (CITIZENSHIP_ID) REFERENCES CITIZENSHIP(ID);

CREATE INDEX IX_DOCUMENT_DOC_TYPE ON DOCUMENT(DOC_TYPE);
ALTER TABLE DOCUMENT ADD FOREIGN KEY (DOC_TYPE) REFERENCES DOC_TYPE(ID);

CREATE INDEX IX_DOCUMENT_USER_ID ON DOCUMENT(USER_ID);
ALTER TABLE DOCUMENT ADD FOREIGN KEY (USER_ID) REFERENCES USER(ID);