CREATE TABLE IF NOT EXISTS Company(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    full_name VARCHAR(255),
    inn INTEGER NOT NULL,
    kpp INTEGER NOT NULL,
    address VARCHAR(255) NOT NULL, phone VARCHAR(255),
    is_active VARCHAR(50) NOT NULL
);